version: '3'
services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
       - ../:/var/www
    command: tail -f /dev/null
    ports:
      - "8080:8080"
